### ISSUE TITLE
`ApacheConfigError` with "<Directory />"

### ISSUE THREAD

**Issue by HorlogeSkynet** [etingof/apacheconfig#11]
Hey, it's me again (already !),

Looks like the ~~lexer~~ parser can't handle config files with something like :
```apache
<Directory />
# ...
</Directory>
```

We got this error thrown :
```python
apacheconfig.error.ApacheConfigError: Parser error at 'Directory'
```

This seems to come from the `>` not separated from the `/`.

Nevertheless, this configuration is likely possible with Apache default files :fearful:

Thanks for your time,
Bye

**Comment by etingof** [comment]
So far I can't reproduce this issue with current master. Could you please make sure you use the latest released `apacheconfig` or even better current master?

Also, is your example syntactically valid? It looks like the first tag does not require the second tag because the first tag is closed by `/>`, no?

**Comment by etingof** [comment]
Ah, right! Let's try commit e999a158ac95d3bfe0c2469f27efa27c9bfbb32c which is current HEAD in master.

WDYT?

**Comment by HorlogeSkynet** [comment]
I can confirm that is woarking like a charm :tada:

I've thought about such a change, but feared breaking something else...

Thanks again, you've just unlocked us :wink:

**Comment by etingof** [comment]
Feel free to experiment and come up with PRs ;)
