### ISSUE TITLE
Reading from a remote host.

### ISSUE THREAD

**Issue by barnabasJ** [etingof/apacheconfig#14]
Hello, 
I was thinking about using your parser to create a new module for [testinfra](https://github.com/philpep/testinfra). But for this to work I would have to read from the target host via a different command then open. If you could give me some pointers on how you would implement this, I would like to create a PR with the changes. 
Thanks in advance
Barnabas

**Comment by etingof** [comment]
Hi there!

Do you mean [this open](https://github.com/etingof/apacheconfig/blob/master/apacheconfig/loader.py#L344)? That's a good point, it should have worked with a file object (like `json.load`) rather than a path.

I'd probably try to modify `load` to branch on the type of its first arg to see if it's a `str` for file system path (to retain backward compatibility for some time) or a file-like object...

WDYT?

**Comment by barnabasJ** [comment]
Yes exactly, although I was thinking more along the line of being able to inject a custom "open" function that returns the file contents as a string given a file path. Because you call the load function for every include statement inside the config if I'm not mistaken. This would give me the ability to write a function that returns the file content from the target host instead of trying to open it on the machine where the code is running.
Looking forward to hearing your opinion.

**Comment by barnabasJ** [comment]
Thanks for the input. Taking all of this into account, I'll try and implement something over the next couple of days and open a PR.
