### ISSUE TITLE
Option for disabling `OPEN_CLOSE_TAG`

### ISSUE THREAD

**Issue by sydneyli** [etingof/apacheconfig#64]
Hiya! So the Apache parser doesn't support the "open/close tag" (AKA empty-element tag) -- that is, using `<block/>` as a shortcut for `<block> </block>`. This enables people to have a section like:
```
<Directory />
</Directory>
```
(a pretty common apache block!) without breaking the parser. Perl's Config::General throws an error when parsing the above since the first line is interpreted as an open/close tag, but Apache's parser is fine with it.

To resolve this conflict, I might propose adding an option to disable OPEN_CLOSE_TAG parsing.

**Comment by etingof** [comment]
Hey Syd!

One thing I am not sure about is [this syntax](https://github.com/etingof/apacheconfig/blob/master/tests/unit/test_parser.py#L225). It is likely to be readily supported, no? Perhaps you have something different in mind...?

Generally, I think it makes sense for us to support everything that Perl version supports, so that the users could transition smoothly. Supporting things conditionally also makes sense to me to cover for use-case that do not need to be backward compatible with Perl behavior.

Thanks!

**Comment by sydneyli** [comment]
> One thing I am not sure about is [this syntax](https://github.com/etingof/apacheconfig/blob/master/tests/unit/test_parser.py#L225). It is likely to be readily supported, no? Perhaps you have something different in mind...?

In Apache, it's possible to have a block like:
```
<Directory /path/to/dir/>
</Directory>
```
Under the current `apacheconfig` and `Config::General` behavior, I think this is interpreted as an OPEN_CLOSE_TAG, then a CLOSE_TAG, which leads to an error. I'll create an option to preserve compatibility with the Perl module's behavior!
